[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "healpix-plotting"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib-base = ">=3.10.8,<4"
numpy = ">=2.4.2,<3"
cartopy = ">=0.25.0,<0.26"
python = "3.14.*"
numpy_groupies = ">=0.11.3,<0.12"
scipy = ">=1.17.0,<2"

[pypi-dependencies]
healpix-plotting = { path = ".", editable = true }

[feature.affine.dependencies]
affine = "*"

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.test.tasks]
tests = { cmd = "pytest --cov=healpix_plotting", default-environment = "default" }

[feature.dev.dependencies]
ipython = "*"
jupyterlab = "*"
black = "*"
jupyter-resource-usage = "*"
jupyterlab_code_formatter = "*"
isort = "*"

[environments]
default = ["test", "dev", "affine"]
